tttt/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.decorators.cache import cache_page
import django.views.static

import apps.api.urls
import apps.core.views
from apps.core.views import (HomePageView, JobDetailView, JobHistoryView,
                             JobsDiffView, JobsListView, TestDetailView,
                             TestsListView)
from apps.kerberos.views import LoginView
from apps.report.views import ReportListView, ReportPageView, ReportAppListView

admin.autodiscover()

CACHE = 0

urlpatterns = [url(r'^xml/(?P<id>[0-9]+)$',
                   apps.core.views.to_xml, name='beaker-xml'),
               url(r'^import/$', apps.core.views.import_xml,
                   name='import-xml'),
               url(r'^import/group$',
                   apps.core.views.import_group, name='import-group'),
               url(r'^api/', include(apps.api.urls)),
               #   url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
               url(r'^tests/(?P<email>.+)$',
                   TestsListView.as_view(), name='tests-email'),
               url(r'^reports/$',
                   ReportListView.as_view(), name='reports'),
               url(r'^reports/apps/$',
                   ReportAppListView.as_view(), name='reports-apps'),
               url(r'^reports/(?P<id>[0-9]+)$',
                   ReportPageView.as_view(), name='report-page'),
               url(r'^accounts/login',
                   LoginView.as_view(), name="login"),
               url(r'^job/(?P<id>[0-9]+)$',
                   cache_page(60 * CACHE)(JobDetailView.as_view()), name='job-detail'),
               url(r'^job_history/(?P<id>[0-9]+)$',
                   JobHistoryView.as_view(), name='job-history'),
               url(r'^test/(?P<id>[0-9]+)$',
                   TestDetailView.as_view(), name='test-detail'),
               url(r'^(Automation/)?[tT]ests.html$',
                   cache_page(60 * CACHE)(TestsListView.as_view()), name='tests-list'),
               url(r'^(Automation/)?[jJ]obs.html$',
                   cache_page(60 * CACHE)(JobsListView.as_view()), name='jobs-list'),
               url(r'^(Automation/)?[dD]iffs.html$',
                   JobsDiffView.as_view(), name='jobs-diff'),
               url(r'^(Automation/?)?$',
                   HomePageView.as_view(), name='homepage'),

               url(r'^%s(?P<path>.*)$' % settings.STATIC_URL[1:],
                   django.views.static.serve,
                   {"document_root": settings.STATIC_ROOT}),

               url(r'^admin/doc/', include(
                   'django.contrib.admindocs.urls')),
               url(r'^admin/', include(admin.site.urls)),
               url(r'^admin/grappelli/', include('grappelli.urls')),
                       ]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

apps/core/forms.py
# Author: Pavel Studenik <pstudeni@redhat.com>
# Date: 24.9.2013

import difflib
import logging
from django import forms
import apps.core.views
from models import GroupTemplate, GroupTestTemplate, JobTemplate, Test

logger = logging.getLogger("main")


class HomepageForm(forms.Form):
    ORDER_CHOICES = (
        ("rate", "rate"),
        ("score", "score")
    )

    def __init__(self, *args, **kwargs):
        super(HomepageForm, self).__init__(*args, **kwargs)
        self.fields['search'].widget.attrs['class'] = 'form-control'
    order = forms.ChoiceField(
        choices=ORDER_CHOICES,
        required=False
    )
    schedule = forms.IntegerField(
        required=False
    )
    page = forms.IntegerField(
        required=False
    )
    search = forms.CharField(
        required=False
    )

    def get_params(self):
        return "&amp;".join(["%s=%s" % (x, y)
                             for x, y in self.cleaned_data.items()])


class FilterForm(forms.Form):
    onlyfail = forms.BooleanField(
        required=False, initial=False
    )
    search = forms.CharField(
        required=False
    )
    tag = forms.CharField(
        required=False
    )
    slider = forms.CharField(
        required=False
    )

    def __init__(self, *args, **kwargs):
        super(FilterForm, self).__init__(*args, **kwargs)
        self.fields['search'].widget.attrs['class'] = 'form-control'
        self.fields['search'].widget.attrs['placeholder'] = 'Search'

    def clean_search(self):
        value = self.cleaned_data["search"].strip()
        return value


class GroupsForm(forms.Form):
    group = forms.ModelChoiceField(
        queryset=GroupTemplate.objects.filter().order_by("name"), empty_label=None)
    content = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'form-control', 'rows': "30", 'cols': "100"}))

    def save(self):
        group = self.cleaned_data["group"]
        tasks = group.grouptests.all().order_by("priority")
        tests_exists = [it.test.name for it in tasks]

        rows = self.cleaned_data["content"]
        priority = len(tests_exists) + 1
        for testname in rows.split():
            try:
                test = Test.objects.get(name=testname.strip())
                if test.name not in tests_exists:
                    gtt = GroupTestTemplate(
                        test=test, group=group, priority=priority)
                    gtt.save()
                    priority += 1

            except Test.DoesNotExist:
                logger.warning("test %s does not exist" % testname)
        return group


class JobForm(forms.Form):
    jobs1 = forms.ModelChoiceField(queryset=JobTemplate.objects.filter(
        is_enable=True).order_by("whiteboard"), empty_label=None)
    jobs2 = forms.ModelChoiceField(queryset=JobTemplate.objects.filter(
        is_enable=True).order_by("whiteboard"), empty_label=None)

    def compare(self):
        d = difflib.HtmlDiff(wrapcolumn=90)
        job1_xml = apps.core.views.get_xml(
            self.cleaned_data["jobs1"]).splitlines(1)
        job2_xml = apps.core.views.get_xml(
            self.cleaned_data["jobs2"]).splitlines(1)
        return d.make_table(job1_xml, job2_xml)

apps/core/views/homepage.py
# Author: Pavel Studenik <pstudeni@redhat.com>
# Date: 24.9.2013

import logging
from datetime import timedelta
from collections import OrderedDict

from django.conf import settings
from django.core.paginator import Paginator
from django.db.models import Count
from django.utils import timezone
from django.views.generic import TemplateView
from elasticsearch import Elasticsearch

from apps.core.forms import HomepageForm
from apps.core.models import (CheckProgress, EnumResult, FileLog, Task,
                              TestHistory, Recipe)
from apps.report.models import Score
from apps.taskomatic.models import TaskPeriodList, TaskPeriodSchedule
from apps.waiver.models import Comment

logger = logging.getLogger(__name__)


class PaganatorSearch:

    def __init__(self, count_objs):
        self.objects = range(count_objs / 10)

    def page(self, page):
        self.actual_page = page
        if page == 1:
            self.has_previous = False
        else:
            self.has_previous = True
            self.previous_page_number = page - 1

        if len(self.objects) < page:
            self.has_next = False
        else:
            self.has_next = True
            self.next_page_number = page + 1
        return self


class HomePageView(TemplateView):
    template_name = 'homepage.html'
    filters = {}
    forms = {}

    def search(self):
        query = self.filters.get("search")
        page = self.filters.get("page")

        if not page:
            page = 1
        if query:
            result = self.es.search(index="testout.log", body={
                "query":
                    {"match":
                        {
                            "content": {
                                "query": "'%s'" % query,
                                "type": "phrase",
                            }
                        }
                     },
                "sort":
                    {"period": "desc"},
                "from": 10 * (page - 1),
                "size": 10
            },
                fields=("_id", "task", "path", "recipe", "period"),
            )
            ids = [int(x["_id"]) for x in result["hits"]["hits"]]

            dict_tmp = dict((x, None) for x in ids)
            for it in FileLog.objects.filter(index_id__in=ids):
                dict_tmp[it.id] = it
            result["result"] = []
            for _id in ids:
                result["result"].append(dict_tmp[_id])
            sp = PaganatorSearch(result["hits"]["total"])
            result["paginator"] = sp.page(page)
            return result

    def get_network_stas(self, **kwargs):
        def get_lab(hostname, num):
            return ".".join(hostname.split(".")[-1 * num:])

        # TODO - show only some last runs
        periods = TaskPeriodSchedule.objects.all().values(
            "title", "date_create", "id", "counter").order_by("title", "-date_create")
        ids = map(lambda x: x["id"], periods)

        tasks = Task.objects.filter(recipe__job__schedule_id__in=ids) \
            .values("result", "recipe__system__hostname", "recipe__job__schedule__id") \
            .annotate(results=Count("result"),
                      hosts=Count("recipe__system__hostname"),
                      label=Count("recipe__job__schedule")) \
            .order_by("recipe__system__hostname", "recipe__job__schedule__id")

        data = {}
        labels = set()
        ER = EnumResult()
        for it in tasks:
            hostname = get_lab(it.get("recipe__system__hostname"), 4)
            schedule = it.get("recipe__job__schedule__id")
            result, count = ER.get(it.get("result")), it.get("hosts")
            labels.add(schedule)
            if hostname in data:
                if schedule not in data[hostname]:
                    data[hostname].update({schedule: {result: count}})
                data[hostname][schedule][result] = count
            else:
                data[hostname] = {schedule: {result: count}}

        for hostname, value in data.items():
            for schedule in labels:
                if not value.get(schedule):
                    data[hostname][schedule] = {}
        return {"labels": labels, "data": data}

    def call_broken_systems(self):
        self.brokensystems = {}
        brokensystems = {}

        tasks = Task.objects.filter(recipe__job__date__gt=timezone.now() - timedelta(days=settings.BROKEN_SYSTEM_DAYS)) \
            .values("result", "recipe__system__hostname") \
            .annotate(results=Count("result"),
                      hosts=Count("recipe__system__hostname")) \
            .order_by("recipe__system__hostname",)

        for it in tasks:
            brokensystems.setdefault(it["recipe__system__hostname"], {}) \
                .setdefault(EnumResult.get(it["result"]), it["results"])
        for key, it in brokensystems.items():
            if not key:
                continue  # system wasn't assigned
            count = 0
            for k, res in it.items():
                if k not in ('fail', 'warning'):
                    continue
                count += res
            positive = 0
            if it.get("pass"):
                positive += it.get("pass")
            if it.get("new"):
                positive += it.get("new")

            # 90 % tasks fail/warning in more than 30 tasks
            MIN_TASK = 30
            FAIL_LIMIT = 0.9
            if count > MIN_TASK and (positive == 0 or count / float(positive + count) > FAIL_LIMIT):  # 90% tasks failed
                self.brokensystems[key] = (
                    count, it.get("pass"), brokensystems[key])

            self.brokensystems = OrderedDict(sorted(self.brokensystems.items()))

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)

        form = HomepageForm(self.request.GET)
        form.is_valid()
        context["forms"] = form
        self.filters = form.cleaned_data
        pag_type = self.request.GET.get('type')

        if settings.ELASTICSEARCH:
            self.es = Elasticsearch(settings.ELASTICSEARCH)
            if self.es.ping():
                context["elasticsearch"] = self.es.info()
            context['search'] = self.search()
        try:
            context['progress'] = CheckProgress.objects.order_by(
                "-datestart")[0]
        except IndexError:
            context['progress'] = None

        # Waiver
        comments = Comment.objects\
            .filter(created_date__gt=timezone.now().date())\
            .order_by("-created_date", "task", "recipe", "job")
        paginator = Paginator(comments, settings.PAGINATOR_OBJECTS_ONHOMEPAGE)
        context['waiver'] = paginator.page(
            int(self.request.GET.get('cpage', 1)))

        history = TestHistory.objects.filter().order_by(
            "-date")[:settings.PAGINATOR_OBJECTS_ONHOMEPAGE * 10]
        paginator = Paginator(history, settings.PAGINATOR_OBJECTS_ONHOMEPAGE)
        context['history'] = paginator.page(
            int(self.request.GET.get('hpage', 1)))

        # context['networking'] = self.get_network_stas()
        ids = [it["max_id"] for it in TaskPeriodList.last_runs()]
        filter_ids = ids
        if self.filters.get("schedule"):
            filter_ids = [int(self.filters.get("schedule"))]
        order = self.filters.get(
            "order") if self.filters.get("order") else "score"

        # Score
        score_obj = Score.objects.filter(
            schedule__in=filter_ids).order_by(order)
        score = Paginator(score_obj, settings.PAGINATOR_OBJECTS_ONHOMEPAGE)

        page = 1
        if "score" == pag_type:
            page = int(self.filters.get('page', 1))
        context["score"] = score.page(int(page))
        range_min = page - 5
        range_range = 10
        if page <= range_range / 2:
            range_min = 1
            range_range += page
        if score.page_range[-1] < range_min + range_range:
            range_min = score.page_range[-1] - range_range
        context["score"].ranges = sorted(set(
            [1, page, score.page_range[-1]]).union(range(range_min, range_min + range_range)))

        context["schedules"] = TaskPeriodSchedule.objects.filter(
            id__in=ids).order_by("period")

        context["files"] = {
            "indexed": FileLog.objects.filter(is_indexed=False, is_downloaded=True).count(),
            "downloaded": FileLog.objects.filter(status_code=0).count()
        }

        self.call_broken_systems()
        context["brokensystems"] = self.brokensystems
        return context

apps/core/views/report.py
# Author: Pavel Studenik <pstudeni@redhat.com>
# Date: 3.2.2016

from django.views.generic import TemplateView
from apps.core.models import GroupTestTemplate, Test, Task
from django.db.models import Max, Count
from apps.taskomatic.models import TaskPeriodSchedule


class ListId:
    @staticmethod
    def running(schedule_ids):
        test_ids = Task.objects\
            .filter(recipe__job__schedule__id__in=schedule_ids)\
            .values("test__id")\
            .annotate(dcount=Count("test"))\
            .order_by("-dcount")
        return [it["test__id"] for it in test_ids]


class ReportListView(TemplateView):
    template_name = 'report.html'

    def get(self, request, *args, **kwargs):
        self.repo = request.GET.get("repo")
        return super(self.__class__, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)

        periods = TaskPeriodSchedule.objects.values("period")\
            .annotate(dmax=Max('id'))

        ids = [it["dmax"] for it in periods]
        tasks = Task.objects.filter(recipe__job__schedule__id__in=ids)\
            .values("result", "recipe__job__schedule__title")\
            .annotate(dcount=Count("result"), scount=Count("recipe__job__schedule"))\
            .order_by("result")

        context["grouptest"] = GroupTestTemplate.objects.values(
            "group__name").annotate(dcount=Count("group")).order_by("-dcount")
        context["repotest"] = Test.objects.values("git__name").annotate(
            dcount=Count("git")).order_by("-dcount")

        running_ids = ListId.running(ids)
        repotask = Test.objects.filter(id__in=running_ids).values(
            "git__name").annotate(dcount=Count("git")).order_by("-dcount")

        keys = dict([(it["git__name"], it["dcount"]) for it in repotask])

        for it in context["repotest"]:
            if it["git__name"] in keys:
                it.update({"run": keys[it["git__name"]]})
                it.update({"notrun": it["dcount"] - keys[it["git__name"]]})

        t = {}
        for it in tasks:
            key = it["recipe__job__schedule__title"]
            if key not in t:
                t[key] = {}
            t[key].update({it["result"]: it["dcount"]})
        context["tasks"] = t

        if self.repo:
            context["nonrun"] = Test.objects.filter(is_enable=True, git__name=self.repo).exclude(id__in=running_ids)

        return context

tttt/templates/detail-panel.html
{% load widget_tweaks %}
<div class="panel-detail {% if detailPanelHidden == "1" %}small{% endif %}" {% if detailPanelHeight >= 100 %}style="height: {{detailPanelHeight}}px"{% endif %}>
	<div class="header">
	  <ul class="nav nav-tabs">
		  <li class="active"><a href="#stab-detail" data-toggle="tab">Details</a></li>
		  <li><a href="#stab-actions" data-toggle="tab">Actions</a></li>
	  </ul>
	  <span class="hTitle">Detail panel</span>
	  <div class="glyphicon glyphicon-chevron-{% if detailPanelHidden == "1" %}up{% else %}down{% endif %} visibilitySwitcher"></div>
	</div>
	<div class="content row tab-content">
		  <div class="tab-panel active" id="stab-detail">
			<ul class="nav nav-tabs nav-stacked tab-detail-header col-xs-2 elastic scrolling"></ul>
			<div class="tab-content tab-detail-content col-xs-10"></div>
		  </div>
		  <div class="tab-panel" id="stab-actions">
			<div class="elastic col-xs-6 recipe-list">
				<h4>Recipes:</h4>
			</div>
			<div class="col-xs-6 action-panel">
				<h4>Actions</h4>
				{% for error in waiveForm.errors.items %}
				  <div  class="alert alert-danger">{{ error|striptags }}</div>
				{% endfor %}
				<form class="form-horizontal" role="form" method="POST">
				  {% csrf_token %}
				  <div class="form-group">
				    <label for="inputName" class="col-sm-2 control-label">Name:</label>
				    <div class="col-sm-10">{% render_field waiveForm.username class="form-control" placeholder="Name" required=None %}</div>
				  </div>
				  <div class="form-group">
				    <label for="inputMessage" class="col-sm-2 control-label">Text:</label>
					<div class="col-sm-10">{% render_field waiveForm.content class="form-control" rows="3" required=None %}</div>
				  </div>
				  <div class="form-group">
				   <div class="col-sm-offset-2 col-sm-10">
				     <button type="submit" class="btn btn-info" disabled="disabled" title="Add new comment" data-action-field="action" data-action-value="{{ waiveClass.ENUM_ACTION_NONE }}">Comment</button>
				     {% if waiveClass.ENUM_ACTION_WAIVED in detailActions %}<button type="submit" class="btn btn-primary" disabled="disabled" title="Waive this jobs." data-action-field="action" data-action-value="{{ waiveClass.ENUM_ACTION_WAIVED }}" data-modalTitle="Warning" data-modalIcon="glyphicon-warning-sign" data-modalQuestion="Are you sure, that you want to waive this job(s)?">Waive</button>{% endif %}
				     {% if waiveClass.ENUM_ACTION_RETURN in detailActions %}<button type="submit" class="btn btn-danger" disabled="disabled" title="Return the resources back to beaker." data-action-field="action" data-action-value="{{ waiveClass.ENUM_ACTION_RETURN }}" data-modalIcon="glyphicon-warning-sign" data-modalTitle="Warning" data-modalQuestion="Are you sure, that you want to return this job(s) to the beaker?">Beaker</button>{% endif %}
				     {% if waiveClass.ENUM_ACTION_RESCHEDULE in detailActions %}<button type="submit" class="btn btn-success" disabled="disabled" title="Stop this job and reschedule it again." data-action-field="action" data-action-value="{{ waiveClass.ENUM_ACTION_RESCHEDULE }}" data-modalIcon="glyphicon-warning-sign" data-modalTitle="Warning" data-modalQuestion="Are you sure, that you want to reschedule this job(s) again?">Reschedule</button>{% endif %}
				   </div>
				 </div>
				 {% render_field waiveForm.action type="hidden" value="" %}
				 {% render_field waiveForm.uids type="hidden" %}
				</form>
			</div>
		  </div>
    </div>
</div>
<div class="modal fade" id="panel-detailModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">
        <p></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
        <button type="button" class="btn btn-primary" data-return="1">Yes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

tttt/templates/diffs.html
{% extends "basic.html" %}

{% block title %}- Job diff{% endblock %}

{% block content %}
<h1>Job Diffs</h1>

<form action="" method="POST" > {% csrf_token %} 
	<table>
{{ form }}
</table>
<br />
<input type="submit" name="submit" value="diff" class="btn btn-primary" />
</form>

{{ diff|safe }}

{% endblock %}

tttt/templates/import_group.html
{% extends "basic.html" %}

{% block title %}Group Template{% endblock %}

{% block content %}

<ul class="nav nav-tabs">
  <li role="presentation" ><a href="{% url 'import-xml' %}">Job Template</a></li>
  <li role="presentation" class="active"><a href="{% url 'import-group' %}">Group Tempalte</a></li>
</ul>

<h1>Group Template</h1>

{% if group %}
<div class="alert alert-info">
<p><b>Administration:</b><a href="{% url 'admin:core_grouptemplate_change' group.id %}" >{{ group }}</a></p>
</div>
{% endif %}

<form action="" method="POST" class="tableform" id="job">{% csrf_token %}   
{{ forms.group }}

{{ forms.content }}

</textarea>

<div style="margin-top: 20px">
<input type="submit" class="btn btn-primary" value="Queue">
</div>

</form>
{% endblock %}

tttt/templates/import_xml.html
{% extends "basic.html" %}

{% block title %}Import Job Template{% endblock %}

{% block content %}

<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="#">Job Template</a></li>
  <li role="presentation"><a href="{% url 'import-group' %}">Group Tempalte</a></li>
</ul>


<h1>Import Job Template</h1>
<h2>{{ job.whiteboard }}</h2>

{% if job %}
<div class="alert alert-info">
	<p><b>Job Template:</b> <a href="{% url 'admin:core_jobtemplate_change' job.id %}" >{{ job.whiteboard }}</a></p>
</div>
<div class="alert alert-info">
	<b>Recipe templates:</b>
	<ul>
	{% for it in recipes %}
		<li><a href="{% url 'admin:core_recipetemplate_change' it.id %}">{{it}}</a></li>
	{% endfor %}
	</ul>
</div>
{% endif %}

{% if error %}<div class="alert alert-danger">{{ error }}</div>{% endif %}
<br> 
<form action="" method="POST" class="tableform" id="job">
    {% csrf_token %}    
    <div style="display:none">
        <input id="job_confirmed" type="hidden" name="confirmed" value="false" class="hiddenfield">
    </div>
<textarea rows="30" cols="100"  name="textxml" id="textxml" class="form-control" >
{{ xml }}
</textarea>

<div style="margin-top: 20px">
<input type="submit" class="btn btn-primary" value="Queue">
</div>

</form>
{% endblock %}

tttt/templates/job-history.html
{% extends "basic.html" %}
{% load core_extras %}

{% block title %}Job history{% endblock %}

{% block content %}

<h1>Job <a href='/admin/core/jobtemplate/{{ job_template.id }}/'>{{ job_template.whiteboard }}</a> history</h1>

{% for period, recipes in data.items %}
    {% for recipe, tests in recipes.items %}
    <h3>{{ recipe }}</h3>
    <table class="dashboard dashboard-tests">
        <caption>{{ period.title }}</caption>
        <thead>
            <tr>
                <th>Test</th>
                {% for schedule in periodschedules|keyvalue:period|dictsort:"counter" %}
                    <th title="Scheduled at {{ schedule.date_create|date:"D Y-m-d" }} {{ schedule.date_create|time:"H:i" }}">{{ schedule.counter }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for test, tasks in tests.items %}
            <tr>
                <th>
                    {{ test.name }}
                    {% if test.get_reposituory_url %}
                        <a href="{{ test.get_reposituory_url }}" class="testInfo">git</a>
                    {% endif %}
                    <a href="{{ test.get_detail_url }}" class="testInfo">detail</a>
                </th>
                {% for schedule in periodschedules|keyvalue:period|dictsort:"counter" %}
                    {% if tasks|keyvalue:schedule.id %}
                        {% with t=tasks|keyvalue:schedule.id %}
                        <td id="T:{{ t.uid }}" class="status-{{ t.get_result }}">
                            <a href="https://{{ conf.BEAKER_SERVER }}/recipes/{{ t.recipe.uid }}#task{{ t.uid }}" class="glyphicon glyphicon-tripledot" title="Link to the task in Beaker">...</a>
                        </td>
                        {% endwith %}
                    {% else %}
                        <td></td>
                    {% endif %}
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endfor %}
{% endfor %}

{% endblock %}

tttt/templates/jobs-list.html
{% extends "basic.html" %}
{% load core_extras %}

{% block title %}- Job Trends{% endblock %}

{% block header %}
<script src="/static/js/core-jobs.js"></script>
{% endblock %}

{% block content %}
<a name="Job Trends"></a>
<h1>Job Trends</h1>
<p>Last check: {{ progress.datestart }}</p>

{% if events %}
{% for event in events %}
<div class="alert alert-{{event.get_alert}}" role="alert">
<b><a href={{event.url}}>{{event.title}}</a></b> {{event.description}} (end is {{event.dateend}})
</div>
{% endfor %}
{% endif %}

{% include 'search-box.html' with onlysearch=1 %}
{% include 'detail-panel.html' %}

<ul class="nav nav-tabs">
  <li role="presentation" {%if not actualtag%}class="active" {% endif %}><a href="{% url "jobs-list" %}">All</a></li>
  {% for tag in tags %}
  <li role="presentation" {%if actualtag == tag.slug %}class="active" {% endif %}><a href="{% url "jobs-list" %}?tag={{tag.slug}}">{{ tag }}</a></li>

  {% endfor %}
</ul>

<h2>Statistic</h2>
<div class="statistic"></div>
<table width="100%">
  <tr>
    <th></th>
    {% for key, it in statistic.label.items %}
    <th>{{ key.isoformat }}</th>
    {% endfor %}
  </tr>
{% for key, it in statistic.data.items %}
  {% if key != "sum"  %}
  <tr>
  <td><b>{{ key }}</b></td>
    {% for k, val in it.items %}
  <td align="center">{{ statistic.data|sum:k|percent:val|floatformat:"1"}}% ({{ val }})</td>
    {% endfor %}
  </tr>
  {% endif %}
{% endfor %}
</table>

<h2>Dashboard <span id="slider-value-info">1</span></h2>
<a name="Dashboard"></a>

<div class="slider">
{{ forms.slider}}
<div id="slider"></div>
</div>


{% for plan in plans %}
<table class="dashboard dashboard-jobs" id="{{plan.object.label}}" >
  <thead>
      <tr><th colspan="{{plan.count|add:2}}"><h4><a href="#{{plan.object.label}}">{{plan.object}}</a></h4></th></tr>
      <tr>
          <th>Job</th>
          <th width="50">Recipe</th>
          {% for key, period in plan.periods.items %}
          <th class="date"><a href="#{{period.id}}" title="{{period.date_create}}" >{{key}}</a></th>
          {% endfor %}
      </tr>
    </thead>
    <tbody>
      {% include "jobs-list-item.html" %}
    </tbody>
</table>
<br>
{% endfor %}

{% include 'legends.html' %}

<script src="http://d3js.org/d3.v3.js"></script>
<script src="/static/js/graph.js"></script>

<script>
  $(function() {
    $( "#slider" ).slider({
      range: "max",
      min: -20,
      max: 0,
      value: 1,
      slide: function( event, ui ) {
        $( "#id_slider" ).val( ui.value );
        $( "#slider-value-info" ).html( ui.value );
      }
    });
  });
</script>

{% endblock %}